// This file is generated by scripts/sync-frontend-env.mjs.
// Do not edit it manually. Update the repository root .env instead.
export const frontendEnv = {
  "apiBaseUrl": "http://localhost:3000/api/v1",
  "assetBaseUrl": "http://localhost:3000",
  "firebasePublicConfig": {
    "apiKey": "AIzaSyBpz1dxm7IJefeezbq7pdib0D9OhUUuaHw",
    "authDomain": "barboo-27dcc.firebaseapp.com",
    "projectId": "barboo-27dcc",
    "appId": "1:830325068393:web:5f833df856e1dd599cc8f8"
  }
} as const;
